name: sac
family: model_free
model:
  _target_: stable_baselines3.SAC
  seed: ${seed}
  device: ${device}
  policy: ${policy.policy}
  policy_kwargs: ${policy.policy_kwargs}
  learning_rate: 3e-4
  buffer_size: 100000
  batch_size: 256
  train_freq: 1
  gradient_steps: 1
  verbose: 1
  tensorboard_log: ${hydra:runtime.output_dir}/${paths.tb}
train:
  total_timesteps: 1000000
agent:
  _target_: agents.baseline.SingleAgent
env_kwargs:
  seed: ${seed}
  num_agents: 1
