defaults:
  - env: racing
  - algo: dqn
  - style: single
  - policy: cnn
  - reward: default
  - wrappers: image_stack
  - callbacks: sb3
  - _self_

seed: 42
project: marl_f1
experiment_name: ${env.name}_${style.name}_${algo.name}_${policy.name}_seed${seed}
device: ${device}
num_threads: 8

paths:
  tb: tb
  checkpoints: checkpoints
  monitor_train: monitor_train
  monitor_eval: monitor_eval
  best_model: best_model
  eval_logs: eval_logs

train_env:
  _target_: stable_baselines3.common.env_util.make_vec_env
  env_id: ${env.id}
  n_envs: 4
  seed: ${seed}
  vec_env_cls: stable_baselines3.common.vec_env.DummyVecEnv
  env_kwargs: ${algo.env_kwargs}
  monitor_dir: ${hydra:runtime.output_dir}/${paths.monitor_train}

eval_env:
  _target_: stable_baselines3.common.env_util.make_vec_env
  env_id: ${env.id}
  n_envs: 1
  seed: ${eval:'${seed} + 1000'}
  vec_env_cls: stable_baselines3.common.vec_env.DummyVecEnv
  env_kwargs: ${algo.env_kwargs}
  monitor_subdir: ${hydra:runtime.output_dir}/${paths.monitor_eval}

train:
  total_timesteps: ${algo.train.total_timesteps}
  tb_log_name: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: experiments/${experiment_name}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: experiments/multirun
    subdir: ${experiment_name}_${hydra.job.num}
  job:
    chdir: false
