train_env:
  _target_: agents.common.build_ss_env
  env_cfg:
    _target_: multi_car_racing.parallel_env
    env_kwargs: ${env_kwargs}
  wrappers:
    - _target_: supersuit.black_death_v3
    - _target_: supersuit.pettingzoo_env_to_vec_env_v1
    - _target_: supersuit.concat_vec_envs_v1
      num_vec_envs: 4
      num_cpus: 1
      base_class: stable_baselines3
    - _target_: stable_baselines3.common.vec_env.VecMonitor
    - _target_: stable_baselines3.common.vec_env.VecFrameStack
      n_stack: 4
    - _target_: stable_baselines3.common.vec_env.VecTransposeImage
    - _target_: stable_baselines3.common.vec_env.VecNormalize
      norm_obs: false
      norm_reward: true
      clip_reward: 10.0

eval_env:
  _target_: agents.common.build_ss_env
  env_cfg:
    _target_: multi_car_racing.parallel_env
    env_kwargs: ${env_kwargs}
  wrappers:
    - _target_: supersuit.black_death_v3
    - _target_: supersuit.pettingzoo_env_to_vec_env_v1
    - _target_: supersuit.concat_vec_envs_v1
      num_vec_envs: 1
      num_cpus: 1
      base_class: stable_baselines3
    - _target_: stable_baselines3.common.vec_env.VecMonitor
    - _target_: stable_baselines3.common.vec_env.VecFrameStack
      n_stack: 4
    - _target_: stable_baselines3.common.vec_env.VecTransposeImage
    - _target_: stable_baselines3.common.vec_env.VecNormalize
      norm_obs: false
      norm_reward: false
      training: false

train:
  total_timesteps: ${algo.train.total_timesteps}
  tb_log_name: ${experiment_name}
  progress_bar: true